const strings = {
    appInfo: {
        seedsVersion: "v2.1.4",
        appVersion: "v2.1.5",
    },
    colorNames: {
        red: "red",
        yellow: "yellow",
        blue: "blue",
        white: "white",
        purple: "purple",
        grey: "grey",
        pink: "pink",
    },
    categoryNames: {
      restaurant: "Restaurant",
      cafe: "Café",
      sweetshop: "Sweetshop",
      movieTheatre: "Movie Theatre",
      pharmacy: "Pharmacy",
      zoo: "Zoo",
      forest: "Forest",
      waterside: "Waterside",
      postOffice: "Post Office",
      artGallery: "Art Gallery",
      airport: "Airport",
      station: "Station",
      beach: "Beach",
      burgerPlace: "Burger Place",
      cornerStore: "Corner Store",
      supermarket: "Supermarket",
      bakery: "Bakery",
      hairSalon: "Hair Salon",
      clothesStore: "Clothes Store",
      park: "Park",
      libraryBookstore: "Library/Bookstore",
      roadside: "Roadside",
      sushiRestaurant: "Sushi Restaurant",
      mountain: "Mountain",
      stadium: "Stadium",
      rainyDay: "Rainy Day",
      snowyDay: "Snowy Day",
      themePark: "Theme Park",
      busStop: "Bus Stop",
      italianRestaurant: "Italian Restaurant",
      ramenShop: "Ramen Shop",
      bridge: "Bridge",
      hotel: "Hotel",
      makeupStore: "Makeup Store",
      shrineTemple: "Shrine/Temple",
      applianceStore: "Appliance Store",
      special: "Special",
    },
    decorNames: {
      chefHat: "Chef Hat",
      chefHatShiny: "Chef Hat (Shiny)",
      coffeeCup: "Coffee Cup",
      macaron: "Macaron",
      popcornSnack: "Popcorn Snack",
      toothbrush: "Toothbrush",
      dandelion: "Dandelion",
      stagBeetle: "Stag Beetle",
      acorn: "Acorn",
      fishingLure: "Fishing Lure",
      stamp: "Stamp",
      pictureFrame: "Picture Frame",
      toyAirplane: "Toy Airplane",
      paperTrain: "Paper Train",
      ticket: "Ticket",
      shell: "Shell",
      burger: "Burger",
      bottleCap: "Bottle Cap",
      snack: "Snack",
      mushroom: "Mushroom",
      banana: "Banana",
      baguette: "Baguette",
      scissors: "Scissors",
      hairTie: "Hair Tie",
      clover: "Clover",
      fourLeafClover: "4-Leaf Clover",
      tinyBook: "Tiny Book",
      marioHat: "Mario Hat",
      lunarNewYearOrnamentRed: "Lunar New Year Ornament (Red)",
      chessPieceWhite: "Chess Piece (White)",
      fingerboard: "Fingerboard",
      flowerCard2023A: "Flower Card 2023 A",
      flowerCard2023B: "Flower Card 2023 B",
      flowerCard2023C: "Flower Card 2023 C",
      flowerCard2023D: "Flower Card 2023 D",
      flowerCard2023E: "Flower Card 2023 E",
      flowerCard2023F: "Flower Card 2023 F",
      stickerGreen: "Sticker (Green)",
      stickerBlue: "Sticker (Blue)",
      stickerOrange: "Sticker (Orange)",
      stickerWinter: "Sticker (Winter)",
      sushi: "Sushi",
      mountainPinBadge: "Mountain Pin Badge",
      leafHatA: "Leaf Hat A",
      leafHatB: "Leaf Hat B",
      leafHatC: "Leaf Hat C",
      themeParkTicketA: "Theme Park Ticket A",
      themeParkTicketB: "Theme Park Ticket B",
      paperBus: "Paper Bus",
      jackOLantern: "Jack-O'-Lantern",
      firstAnniversarySnack: "1st Anniversary Snack",
      koppaiteSpaceSuit: "Koppaite Space Suit",
      ballKeychain: "Ball Keychain",
      mitten: "Mitten",
      glasses2023: "2023 Glasses",
      lunarNewYearOrnamentGold: "Lunar New Year Ornament (Gold)",
      valentineSticker: "Valentine Sticker",
      pizza: "Pizza",
      coin: "Coin",
      easterEgg: "Easter Egg",
      ramenKeychain: "Ramen Keychain",
      presentStickerGold: "Present Sticker (Gold)",
      sneakerKeychain: "Sneaker Keychain",
      bridgeBadge: "Bridge Badge",
      donut: "Donut",
      chessPieceBlack: "Chess Piece (Black)",
      pikmin4Spaceship: "Pikmin 4 Spaceship",
      mahjongTileA: "Mahjong Tile A",
      mahjongTileB: "Mahjong Tile B",
      hotelAmenities: "Hotel Amenities",
      iceCream: "Ice Cream",
      makeup: "Makeup",
      halloweenTreat: "Halloween Treat",
      fortuneA: "Fortune A (大吉)",
      fortuneB: "Fortune B (中吉)",
      fortuneC: "Fortune C (小吉)",
      fortuneD: "Fortune D (吉)",
      fortuneE: "Fortune E (末吉)",
      puzzle2021FallMemories: "Puzzle: 2021 Fall Memories",
      puzzle2022SummerMemories: "Puzzle: 2022 Summer Memories",
      batteryA: "Battery A",
      batteryB: "Battery B",
      batteryC: "Battery C",
      batteryD: "Battery D",
      batteryE: "Battery E",
      batteryF: "Battery F",
      fairyLightsA: "Fairy Lights A",
      fairyLightsB: "Fairy Lights B",
      snow: "Snow",
      glasses2024: "2024 Glasses",
      flowerCard2024A: "Flower Card 2024 A",
      flowerCard2024B: "Flower Card 2024 B",
      reverseValentinesDaySticker: "Reverse Valentine's Day Sticker"
    },
  };

  export default strings;